### ISSUE TITLE
Fitness and multionomial draw

### ISSUE THREAD

**Issue by ldutoit** [colin-olito/XvAutosomeInversions#5]
I coded my version of autoInvFwdSim in functions-WFSims-Autosomal-SexSpec.R  , calling it  autoInvFwdSimSexSpec. I am struggling especially with two points, should the average fitness be calculated across sexes  and is the multinomial draw similar now that we have two sexes (Line 316-323)... Probably not as a custom test with a ridiculously fit mutation does not fix the mutation,

**Comment by colin-olito** [comment]
Hi Ludo,

I can take a closer look tomorrow, or maybe Friday. But A couple quick thoughts in the meantime:

(1) I would probably calculate each: wbar_m, wbar_f, and W_bar (across sexes), and store all three. This will require slight modification to the storage structures etc. but nothing difficult.
(2) Did you set m = 0 for your custom test with a 'ridiculously fit' mutation? Also, what kind of frequency was it segregating at? With m > 0, we will never get fixation in these models.

**Comment by ldutoit** [comment]
Cool! This issue feature is pretty neat.

(1) I did store all three. I am just not 100% wether the mean fitness for the selection stage should be calculated across sexes or not. I feel like I did it right but not 100% sure.

(2) yes m=0, but I just think it is wrong cause the expected and observed fitness deviated from each other much more than reasonable from a draw.

**Comment by colin-olito** [comment]
Hi Ludo,

OK. i noticed a couple things. 

(1) typo: L. 317:  you have the number 'zero' where you meant to have the letter 'O':

    Wbar   <-  0.5 * (sum(O*Wx)+sum(**_# 0_***Wy))

(2) On L. 319 -- 320, I believe the change in frequency due to selection in each sex should be standardized by the sex-specific mean fitness. ie.:

    # 4) Expected frequencies
    E.Fiix  <-  O*Wx/Wbar.x # sex specific expected freq
    E.Fiiy  <-  O*Wy/Wbar.y # sex specific expected freq
where
    Wbar.x  <-  sum(O*Wx)
    Wbar.y  <-  sum(O*Wy)

(3)  My last comment is half nit-picky coding, and half personal preference, but I would maybe suggest changing the way you are subscripting things. Remember, in step #1 we are calculating haplotype frequencies among female and male gametes (hence our xi and yi functions). However, at all the other steps, we are dealing with genotypic frequencies. For this, it makes more sense to me to subscript using f and m for 'females' and 'males'. Using variable names like E.Fiix can be confusing because Fii refers to gentotypes while xi refers to haplotypes. It would also be more consistent with literature for things like Wf and Wm. In the end, x and y are kind of stand-ins for f and m... but using f and m might avoid some potential confusion. It's up to you though. It's not that big a deal, as long as you are consistent.

**Comment by ldutoit** [comment]
(1) my bad, great thank you!

(2) Good, that is one simple point I was struggling with.

(3).It is a valid point, I think I will finish going through and then I would rename all these variables at once.

Thanks for having a look

Ludo
