### ISSUE TITLE
It runs... but...

### ISSUE THREAD

**Issue by ldutoit** [colin-olito/XvAutosomeInversions#7]
The Sex specific model can "run", but I have a few questions.

(1) We have two sexes. How do we want to introduce the mutation. Now it is always done in females line 548, maybe wrong btw ( I migrate 1/n,).

(2) If  the inversion disappears, it gets weird
 the average fitness get to 0, I do not understand. Is that an error in my script ?
```
finalInvFreq finalE.InvFreq finalW.mean finalWx.mean finalWy.mean
1        0.001      0.0010000    0.000000     0.000000     0.000000
 finalInvFreqx finalInvFreqy finalE.InvFreqx finalE.InvFreqy nGen InvEst
1         0.000         0.000       0.0000000       0.0000000    2      0
  InvEstTime nDels
1         NA     2
 ```

(3) Do we want to be able to  save travejctories in makeReplicateAutoInvSimsData ( i.e.the big wrapper) or is it just to test the other functions? I ask cause for now it is not possible in the autosomal case neither, and it seems a bit computer intensive.

Thank you so much for your help.

We can also Skype if you prefer.  I'll look at my code a bit more tomorrow but not sure what the next step is.

Cheers

**Comment by colin-olito** [comment]
Hi Ludo,

(1) We can ask Tim about this, but my first impression is to do it the same way I've set up the 
introduction of mutant inversions in the Autosomal model -- make it random (with an option to specify), and then let any differences arising from the sex where the mutation originates average out over the replicate simulations.  You can take a look at the way I implemented this by looking at the master branch --> functions-WFSims-Autosomal.R --> L.345-392 & L.468. For the Sex-Specific model, we would just need to start with a step similar to L.385, only the outcome of the 'coin flip' would determine whether we introduce the inversion to Fii.init.f or Fii.ini.m.  Make sense?  Let me know if this is something you would like to tackle, or if you'd like me to work on it, because it looks like you will still need to incorporate the `introduceInversion()` function altogether.

(2) I'm not sure what's going on here. I'd need to see a minimal example. Maybe something we can discuss over Skype?

(3) Actually, this is by design. As you rightly point out, saving Trajectories is extremely memory intensive. That is why I set saveTrajectories = FALSE as the default in both `autoInvFwdSim()` and `runReplicateAutoInvSims()`. By the time we are running `makeReplicateAutoInvSimsData()`, we are running so many replicate simulations that it would be silly to save trajectories. The main purpose of the saveTrajectory arg was to make it possible for us to save individual simulations as time-series, both for the purposes of debugging, and in case we wanted to make figures showing individual realizations of the simulations. But it really is not intended to be used once you are running more than about 1000 replicate simulations (see the warning on L.450-455).

**Comment by ldutoit** [comment]
great!

thank you for that. Maybe it would be good to soon look at it, I explain
you what I did and as we go along we can catch  mistakes so we are ready to
run the simulations. What do you say? When do you have time next week?

Ludk


On 18/02/2018 08:54, "Colin Olito" <notifications@github.com> wrote:

Hi Ludo,

(1) We can ask Tim about this, but my first impression is to do it the same
way I've set up the
introduction of mutant inversions in the Autosomal model -- make it random
(with an option to specify), and then let any differences arising from the
sex where the mutation originates average out over the replicate
simulations. You can take a look at the way I implemented this by looking
at the master branch --> functions-WFSims-Autosomal.R --> L.345-392 &
L.468. For the Sex-Specific model, we would just need to start with a step
similar to L.385, only the outcome of the 'coin flip' would determine
whether we introduce the inversion to Fii.init.f or Fii.ini.m. Make sense?
Let me know if this is something you would like to tackle, or if you'd like
me to work on it, because it looks like you will still need to incorporate
the introduceInversion() function altogether.

(2) I'm not sure what's going on here. I'd need to see a minimal example.
Maybe something we can discuss over Skype?

(3) Actually, this is by design. As you rightly point out, saving
Trajectories is extremely memory intensive. That is why I set
saveTrajectories = FALSE as the default in both autoInvFwdSim() and
runReplicateAutoInvSims(). By the time we are running
makeReplicateAutoInvSimsData(), we are running so many replicate
simulations that it would be silly to save trajectories. The main purpose
of the saveTrajectory arg was to make it possible for us to save individual
simulations as time-series, both for the purposes of debugging, and in case
we wanted to make figures showing individual realizations of the
simulations. But it really is not intended to be used once you are running
more than about 1000 replicate simulations (see the warning on L.450-455).

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/colin-olito/XvAutosomeInversions/issues/7#issuecomment-366467099>,
or mute the thread

**Comment by colin-olito** [comment]
Hi Ludo,

Sounds good. Next week my schedule is flexible except for Monday. Does somewhere in the ballpark of 11am my time (9:30am + 1 day for you) work?

**Comment by ldutoit** [comment]
It would work any day at 930 for me i believe. Or did you mean om your
monday?

Ludo

**Comment by colin-olito** [comment]
OK, let's plan for 11:30 am on my Tuesday = 9:30am on your Wednesday.  Sound good?

**Comment by ldutoit** [comment]
Cool!


Ludo
